// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcktNoBgQ1U5NV8n6iY4q_k59hDCPN_0',
    appId: '1:1061876049070:ios:e08f2a774db9080134393f',
    messagingSenderId: '1061876049070',
    projectId: 'my-portfolio-71070',
    authDomain: 'my-portfolio-71070.firebaseapp.com',
    storageBucket: 'my-portfolio-71070.firebasestorage.app',
    androidClientId: 'com.ashishchauhan.my_portfolio',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcZi2XqRZRsUQyHkLgz9l6nKSnGlOOK8Y',
    appId: '1:1061876049070:ios:e08f2a774db9080134393f',
    messagingSenderId: '1061876049070',
    projectId: 'my-portfolio-71070',
    authDomain: 'my-portfolio-71070.firebaseapp.com',
    storageBucket: 'my-portfolio-71070.firebasestorage.app',
    iosBundleId: 'com.ashishchauhan.myPortfolio',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5CgSIQqsT4xMpnolb89yEEUINPRffj0',
    appId: '1:1061876049070:web:8d6c040b4352bee234393f',
    messagingSenderId: '1061876049070',
    projectId: 'my-portfolio-71070',
    authDomain: 'my-portfolio-71070.firebaseapp.com',
    storageBucket: 'my-portfolio-71070.firebasestorage.app',
    measurementId: 'G-8DP95QZ5GT',
  );
}
